### ISSUE TITLE
Add all missing pages

### ISSUE THREAD

**Issue by SPLATPLAYS** [KSHS-Robotics-Club/kshs-robotics-club.github.io#24]
This is self explanatory

**Comment by SPLATPLAYS** [comment]
@spacey-sooty How should I interface the contact us page?

**Comment by spacey-sooty** [comment]
Have any public way to contact as linked I'll make a team email, link Insta etc

**Comment by SPLATPLAYS** [comment]
The contact page be a few links to (well contact services), and I'll add a contact form below aswell

**Comment by spacey-sooty** [comment]
Sure make that send to a private channel on discord then, easier for me to check and keep track of

**Comment by SPLATPLAYS** [comment]
kk
